version: '3.8'

services:
  frontend:
    container_name: frontend
    ports:
      - "3000:3000"
    image: react_app2
    command: npm start

  backend:
    container_name: backend
    ports:
      - "80:3000"
    image: react_app2
    command: node index.js