name: Practise

run-name: ${{github.actor}} iniating workflow.

on:
  push:
    branches:
    - main

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checking out
        uses: actions/checkout@v4

      - name: setting up nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: install dependancies
        run: npm install

      - name: build app
        run: npm run build-react

      - name: rsync deployments
        uses: burnett01/rsync-deployments@6.0.0
        with:
          switches: -avzr --delete
          path: src/
          remote_path: /home/ubuntu/
          remote_host: 3.239.174.136
          remote_user: ubuntu
          remote_key: ${{ secrets.PRACTISE_KEY }}

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.1
        with:
          host: 3.239.174.136
          username: ubuntu
          key: ${{ secrets.PRACTISE_KEY }}
          port: 22
          script: |
            docker build -t react_app2 .
            docker compose down
            docker compose up
